# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5521a56f853b8af0e50843431aba8aeea27115cf07448e1aafe2ade40a48570d698fedfc04c05de9d65576074d09b8c14e2f979f503fd601ae0276020dfca566

test:
  secret_key_base: 916c9d06b6e231c4b5bf5929fdeece17d1627298a89903cae8814afdf14b5a8cdcf24498394200692e0f554982d83a3ad9eb414852ea8dae1934f26ebe0f3b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
